name: locale
on: [push]

jobs:
  locale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install wct
        run: npm install --location=global wow-curse-tools

      - name: scan locales
        run: wct locale scan

      - name: upload locales
        run: wct locale import --token ${{ secrets.CURSE_TOKEN }}

      - name: download locales
        run: wct locale export --token ${{ secrets.CURSE_TOKEN }}

      - uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          commit_message: "chore: Update locale files"
          tags: false

