name: Update 🧀
on:
  push:
    branches:
      - master
    tags-ignore:
      - "v*"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update libs
        uses: curse-action/update@master
        with:
          curse-forge-token: ${{ secrets.CURSE_FORGE_TOKEN }}

      - name: Update locales
        uses: curse-action/locale@master
        with:
          curse-wow-token: ${{ secrets.CURSE_TOKEN }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: Update libs/locale/data files"
