name: Auto update locales 🌏
on:
  push:
    branches:
      - master
    tags-ignore:
      - "v*"
    paths:
      - "**.lua"
      - .github/workflows/update-locales.yml

jobs:
  update-locales:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update locales
        uses: curse-action/locale@master
        with:
          curse-wow-token: ${{ secrets.CURSE_TOKEN }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: Update locale files"
